spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}

app:
  rabbitmq:
    sesion:
      exchange: ${RABBITMQ_SESION_EXCHANGE:hotel.events}
      login-routing-key: ${RABBITMQ_LOGIN_ROUTING_KEY:user.login}
      registered-routing-key: ${RABBITMQ_REGISTERED_ROUTING_KEY:user.registered}
      password-reset-routing-key: ${RABBITMQ_PASSWORD_RESET_ROUTING_KEY:user.password.reset}
  notifications:
    sesion:
      enabled: ${NOTIFICATION_SESION_ENABLED:true}

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/v1

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:}
      expiration: ${JWT_EXPIRATION:3600}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400}
    password-reset-expiration-minutes: ${PASSWORD_RESET_EXPIRATION_MINUTES:15}
    password-reset-max-attempts: ${PASSWORD_RESET_MAX_ATTEMPTS:3}
    password-reset-block-minutes: ${PASSWORD_RESET_BLOCK_MINUTES:15}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
